[project]
name = "python-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=0.37.1",
    "ipykernel>=7.1.0",
    "langchain>=1.2.0",
    "langchain-groq>=1.1.1",
]
